### ISSUE TITLE
How does this differ from AVQueuePlayer?

### ISSUE THREAD

**Issue by ryanmasondavies** [tonyzonghui/AudioPlayer#2]

**Comment by tonyzonghui** [comment]
For some format of audio files like mp3 there is a slight gap (about tens of milliseconds) in front and at back of the file. If you want to play a few of these files gaplessly, this can help. This library trims the blank period which contains no data from the audio source file. For example, if you want to chop a song into pieces and want to play them in sequence to make it sounds exactly like the original song, this can help.
